# This rule is not used by the project custome-role-crd itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over custom-rbac.improwised.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: custome-role-crd
    app.kubernetes.io/managed-by: kustomize
  name: customrole-admin-role
rules:
- apiGroups:
  - custom-rbac.improwised.com
  resources:
  - customroles
  verbs:
  - '*'
- apiGroups:
  - custom-rbac.improwised.com
  resources:
  - customroles/status
  verbs:
  - get
