# This rule is not used by the project custome-role-crd itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the custom-rbac.improwised.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: custome-role-crd
    app.kubernetes.io/managed-by: kustomize
  name: customrole-editor-role
rules:
- apiGroups:
  - custom-rbac.improwised.com
  resources:
  - customroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - custom-rbac.improwised.com
  resources:
  - customroles/status
  verbs:
  - get
